FROM node:16-alpine

ENV NODE_ENV production
LABEL version="1.0"
LABEL description="This is the base docker image for back api Gallery."

WORKDIR /app

COPY package.json  /app

RUN npm install

COPY . /app


EXPOSE 3001

CMD [ "npm", "run", "serve" ]